### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by npc-glitch** [voidcase/txtv#6]
I get this error when trying to run txtv with Python version 3.9.5-2

`Traceback (most recent call last):
  File "/home/seb/.local/bin/txtv", line 8, in <module>
    sys.exit(run())
  File "/home/seb/.local/lib/python3.9/site-packages/txtv/txtv.py", line 224, in run
    interactive(Page(100))
  File "/home/seb/.local/lib/python3.9/site-packages/txtv/txtv.py", line 24, in __init__
    pn_links = soup.find('form', id='navform').find_all('a')
AttributeError: 'NoneType' object has no attribute 'find_all'
`

**Comment by voidcase** [comment]
Well fuck. I guess SVT finally updated their text-tv page, breaking txtv. It appears the old format is still available in the form of a screenreader tag. This will mean some relatively big changes to txtv. Thanks for reporting it.

**Comment by voidcase** [comment]
Ok, I updated it to use the screenreader data from the site which naturally doesn't have color information so txtv doesn't look as nice as it used to :(
At least it works now.
